weights: yolov5/weights/yolov5s.pt
cfg: yolov5/models/yolov5s.yaml
data: symbol_detection.yaml
hyp: ./yolov5/data/hyp.scratch.yaml
epochs: 50
batch_size: 16
img_size:
- 1024
- 1024
rect: true
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
name: ''
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/
workers: 8
total_batch_size: 16
world_size: 1
global_rank: -1
